FROM container-registry.oracle.com/os/oraclelinux:8-slim

RUN microdnf update && \
    microdnf module enable ruby:3.3 && \
    microdnf install ruby ruby-devel rubygems make gcc glibc system-rpm-config git openssl-devel && \
    microdnf install --enablerepo=ol8_codeready_builder libyaml-devel && \
    microdnf module reset ruby && \
    microdnf clean all

RUN gem install --no-document bundler && \
    gem cleanup

CMD ["ruby", "-v"]

