FROM docker-remote.artifactory.oci.oraclecorp.com/ruby:2.7.3-alpine3.12
RUN apk add --no-cache wget curl alpine-sdk bash
RUN mkdir /build
COPY . /build
WORKDIR /build

RUN gem install --development *.gem